<style>

</style>

<div class="bbgges">
    <div class="dotts">
        <div class="container breadc">
            <div class="cn" style="display: none">
                <div class="row">
                    <div class="col-xs-12">
                        <a href="/">首页</a>
                        <span class="xsplt">/</span>
                        <span class="xsexp">关于普源</span>
                    </div>
                </div>
            </div>
            <div class="en" style="display: none">
                <div class="row">
                    <div class="col-xs-12">
                        <a href="/?language=en">Home</a>
                        <span class="xsplt">/</span>
                        <span class="xsexp">About us</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="cn" style="display: none">
                <div class="row">
                <div class="col-xs-3">
                    <ul class="sid-ul-lst" id="about-us-list-ul">
                        <li class="selected" rel="company_culture">
                            <a href="javascript:void(0)">
                                企业文化
                            </a>
                        </li>
                        <li id="company_profile_li" rel='company_profile'>
                            <a href="javascript:void(0)">
                                公司简介
                            </a>
                        </li>
                        <li rel="our_footprint">
                            <a href="javascript:void(0)">
                                普源在全国
                            </a>
                        </li>
                        <li rel="factory_views">
                            <a href="javascript:void(0)">
                                工厂纵览
                            </a>
                        </li>
                        <li rel="team_spirit">
                            <a href="javascript:void(0)">
                                团队·家
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-9">
                    <div class="about-blks">
                        <div class="about-blk selected" id="company_culture">
                            <p class="tt">企业文化 &gt;&gt;</p>
                            <div class="ab-tab">
                                <div class="ab-row">
                                    <div class="ab-cell col1">企业愿景：</div>
                                    <div class="ab-cell col2">做行业产品专家，致力于为客户提供价值领先的产品和服务</div>
                                </div>
                                <div class="ab-row">
                                    <div class="ab-cell col1">核心价值观：</div>
                                    <div class="ab-cell col2">创新、诚信、务实、重质量、信誉至上</div>
                                </div>
                                <div class="ab-row">
                                    <div class="ab-cell col1">经营理念：</div>
                                    <div class="ab-cell col2">务实创新，追求卓越，一切从客户的利益出发</div>
                                </div>
                                <div class="ab-row">
                                    <div class="ab-cell col1">质量方针：</div>
                                    <div class="ab-cell col2">追求最佳成本、先进技术、优秀管理、优质服务、持续改进和诚心诚意满足顾客对质量日益增高的期望</div>
                                </div>
                                <div class="ab-row">
                                    <div class="ab-cell col1">管理理念：</div>
                                    <div class="ab-cell col2">关爱员工成长，与公司齐进步</div>
                                </div>
                            </div>
                        </div>

                        <div class="about-blk" id="company_profile">
                            <p class="tt"><?php echo $this->model[0]["title"] ?> &gt;&gt;</p>
                            <div class="profile_content">
                                <?php echo $this->model[0]["content"] ?>
                            </div>
                            <div class="clear-10"></div>
                            <img src="img/abo-b.jpg" width="100%"/>
                        </div>

                        <div class="about-blk" id="our_footprint">
                            <p class="tt">普源在全国 &gt;&gt;</p>
                            <img style="max-width: 100%;margin-bottom:20px;" src="img/footerprint.png" />
                            <div class="profile_content">
                                普源坚持“立足深圳、辐射全国”的经营策略，以扎实的专业技能和诚恳的服务精神，公司业务遍及北京、天津、大连、重庆、江苏、昆明、南昌、上海、广州等地。
                            </div>
                        </div>


                        <div class="about-blk" id="factory_views">
                            <p class="tt">工厂纵览 &gt;&gt;</p>
                            <div class="profile_content" style="height:500px;">
                                <div style="position:absolute;left:0;top:10px;background:url(img/6b1.png) center center no-repeat;width:400px;height:345px;">
                                    <p class="brwioie">工厂器械</p>
                                </div>

                                <div style="position:absolute;right:0;top:30px;background:url(img/6b3.png) center center no-repeat;width:350px;height:303px;">
                                    <p class="brwioie">装货运载</p>
                                </div>
                                <div style="position:absolute;right:50%;margin-right:-125px;top:280px;background:url(img/6b2.png) center center no-repeat;width:200px;height:173px;">
                                    <p class="brwioie">产品加工</p>
                                </div>
                            </div>
                        </div>

                        <div class="about-blk" id="team_spirit">
                            <p class="tt">团队·家 &gt;&gt;</p>
                            <div class="profile_content" style="height:700px;">
                                <div class="famlines" style="left:25px;top:45px;">
                                    <span>员工讨论</span>
                                </div>
                                <div class="famlines t2" style="left:370px;top:0;">
                                    <span>会议交流</span>
                                </div>
                                <div class="famlines t2" style="left:550px;top:90px;">
                                    <span>会议交流</span>
                                </div>
                                <div class="famlines t2" style="left:550px;top:300px;">
                                    <span>集体活动</span>
                                </div>
                                <div class="famlines t3" style="left:90px;top:320px;">
                                    <span>集体活动</span>
                                </div>
                                <div class="famlines t3" style="left:480px;top:auto;bottom:110px;">
                                    <span>会议交流</span>
                                </div>
                                <div class="famlines t3" style="left:90px;top:520px;">
                                    <span>集体活动</span>
                                </div>
                                <img src="img/fam.png" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="en" style="display: none">
                <div class="row">
                    <div class="col-xs-3">
                        <ul class="sid-ul-lst" id="about-us-list-ul">
                            <li class="selected" rel="company_culture_en">
                                <a href="javascript:void(0)">
                                    Company Culture
                                </a>
                            </li>
                            <li id="company_profile_en_li" rel='company_profile_en'>
                                <a href="javascript:void(0)">
                                    Company Profile
                                </a>
                            </li>
                            <li rel="our_footprint_en">
                                <a href="javascript:void(0)">
                                    Our Footprint In China
                                </a>
                            </li>
                            <li rel="factory_views_en">
                                <a href="javascript:void(0)">
                                    Factory Views
                                </a>
                            </li>
                            <li rel="team_spirit_en">
                                <a href="javascript:void(0)">
                                    Team Spirit·Family culture
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-9">
                        <div class="about-blks">
                            <div class="about-blk selected" id="company_culture_en">
                                <p class="tt">Company Culture &gt;&gt;</p>
                                <div class="ab-tab">
                                    <div class="ab-row">
                                        <div class="ab-cell col1">Corporate Vision：</div>
                                        <div class="ab-cell col2">Become the leader of sandwich panel in the construction industry, concentrate on offering our customers advanced products and services.</div>
                                    </div>
                                    <div class="ab-row">
                                        <div class="ab-cell col1">Core Values：</div>
                                        <div class="ab-cell col2">Innovation, Integrity, Practicality, Quality, Credibility</div>
                                    </div>
                                    <div class="ab-row">
                                        <div class="ab-cell col1">Business Philosophy：</div>
                                        <div class="ab-cell col2">Practicality and innovation, striving for excellence and take consumer values as first priority.</div>
                                    </div>
                                    <div class="ab-row">
                                        <div class="ab-cell col1">Quality Policy：</div>
                                        <div class="ab-cell col2">Seek optimal cost, advanced technology, excellent management, high-quality services, and continuously improve and satisfy customer's increasing quality expectation.</div>
                                    </div>
                                    <div class="ab-row">
                                        <div class="ab-cell col1">Management Philosophy：</div>
                                        <div class="ab-cell col2">Care for employee's development and make progress together.</div>
                                    </div>
                                </div>
                            </div>

                            <div class="about-blk" id="company_profile_en">
                                <p class="tt"><?php echo $this->model[0]["title_en"] ?> &gt;&gt;</p>
                                <div class="profile_content">
                                    <?php echo $this->model[0]["content_en"] ?>
                                </div>
                                <div class="clear-10"></div>
                                <img src="img/abo-b.jpg" width="100%"/>
                            </div>

                            <div class="about-blk" id="our_footprint_en">
                                <p class="tt">Our Footprint In China &gt;&gt;</p>
                                <img style="max-width: 100%;margin-bottom:20px;" src="img/footerprint.png" />
                                <div class="profile_content">
                                    Sticking to the operational strategy of "based on shenzhen and radiating the profound influence all over the country" and with solid professional skills and sincere service spirit, company operates in Beijing, Tianjin, Dalian, Chongqing, Jiangsu, Kunming, Nanchang, Shanghai, Guangzhou and Foshan cities.
                                </div>
                            </div>


                            <div class="about-blk" id="factory_views_en">
                                <p class="tt">Factory Views &gt;&gt;</p>
                                <div class="profile_content" style="height:500px;">
                                    <div style="position:absolute;left:0;top:10px;background:url(/img/6b1.png) center center no-repeat;width:400px;height:345px;">
                                        <p class="brwioie">Facilities</p>
                                    </div>

                                    <div style="position:absolute;right:0;top:30px;background:url(/img/6b3.png) center center no-repeat;width:350px;height:303px;">
                                        <p class="brwioie">Packing</p>
                                    </div>
                                    <div style="position:absolute;right:50%;margin-right:-125px;top:280px;background:url(img/6b2.png) center center no-repeat;width:200px;height:173px;">
                                        <p class="brwioie">Products Processing</p>
                                    </div>
                                </div>
                            </div>

                            <div class="about-blk" id="team_spirit_en">
                                <p class="tt">Team Spirit·Family culture &gt;&gt;</p>
                                <div class="profile_content" style="height:700px;">
                                    <div class="famlines" style="left:25px;top:45px;">
                                        <span>Discussion</span>
                                    </div>
                                    <div class="famlines t2" style="left:370px;top:0;">
                                        <span>Meeting</span>
                                    </div>
                                    <div class="famlines t2" style="left:550px;top:90px;">
                                        <span>Meeting</span>
                                    </div>
                                    <div class="famlines t2" style="left:550px;top:300px;">
                                        <span>Team building</span>
                                    </div>
                                    <div class="famlines t3" style="left:90px;top:320px;">
                                        <span>Team building</span>
                                    </div>
                                    <div class="famlines t3" style="left:480px;top:auto;bottom:110px;">
                                        <span>Meeting</span>
                                    </div>
                                    <div class="famlines t3" style="left:90px;top:520px;">
                                        <span>Team work</span>
                                    </div>
                                    <img src="img/fam.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#about-us-list-ul li').click(function(){
            var tar = $(this).closest('li');
            var rel = tar.attr('rel');
            var obj = $('#' + rel);
            $('#about-us-list-ul li.selected').removeClass('selected');
            $('.about-blk.selected').removeClass('selected');
            obj.addClass('selected');
            tar.addClass('selected');


        });

        var url = location.href;

        if (url.indexOf("ref=profile") > -1) {
            if (url.indexOf("language=en") > -1) {
                $("#company_profile_en_li").click();
            }
            else {
                $("#company_profile_li").click();
            }
        }

        $(".header").find(".selected").removeClass("selected");
        $(".header").find(".about").addClass("selected");
    });
</script>