<div class="p16-xeet">
    以下是您申请成为老师的提交和审核记录
</div>
<div class="p16-tbx">
    <div class="row">
        <div class="td col1">8月1日</div>
        <div class="td">
            <div class="tt">请被拒绝</div>
            <div class="reject-reason">
                您的个人资料填写不完善，请重新填写
            </div>
            <a href="p15_apply-success.html" class="fullbtn">重新填写</a>
        </div>
    </div>
    <div class="row">
        <div class="td col1">7月16日</div>
        <div class="td">
            <div class="tt">审核中</div>
        </div>
    </div>
    <div class="row">
        <div class="td col1">7月15日</div>
        <div class="td">
            <div class="tt">申请提交</div>
        </div>
    </div>
</div>
<div class="clear-15"></div>
<div class="fullbtn cd_hottap" hottap="p10_me.html">返回</div>

<div class="bt-distance"></div>