<div class="p14-t01">
    您提交的资料都会经过严格审核，请认真填写后再提交。
</div>

<div class="blackrowgall">
    <div class="row">
        <span class="tt">真实姓名</span>
        <input placeholder="请填写真实姓名" value="张三丰" type="text" class="holder" />
    </div>
    <div class="row actbtn cd-slideoutbtn" rel="#pp-change-tel">
        <span class="tt">手机</span>
        <div class="holder arr">
            <span>18923833647</span>
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">性别</span>
        <div class="holder">
					<span>
						<input type="radio" id="p14-male" name="gener"/><label for="p14-male">男</label>
						&nbsp;&nbsp;
						<input type="radio" id="p14-female" name="gener"/><label for="p14-female">女</label>
					</span>
        </div>
    </div>
    <div class="row">
        <span class="tt">出生日期</span>
        <input placeholder="请填写出生日期" value="" type="date" class="holder" />
    </div>
    <div class="row">
        <span class="tt">籍贯</span>
        <input placeholder="请填写籍贯" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">学历</span>
        <select class="holder p14-sele">
            <option>选择学历</option>
            <option>博士</option>
            <option>研究生</option>
            <option>大学</option>
            <option>高中</option>
            <option>初中</option>
        </select>
    </div>
    <div class="row">
        <span class="tt">身份证号码</span>
        <input placeholder="填写正确身份证号码" value="" type="text" class="holder" />
    </div>
</div>

<div class="blackrowgall">
    <div class="row">
        <span class="tt">邮箱</span>
        <input placeholder="请填写常用邮箱" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">QQ（可选）</span>
        <input placeholder="请填写QQ" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">微信（可选）</span>
        <input placeholder="请填写微信号" value="" type="text" class="holder" />
    </div>
</div>


<div class="blackrowgall">
    <div class="row">
        <span class="tt">所在城市</span>
        <input placeholder="请填写" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">授课区域</span>
        <input placeholder="请填写授课区域" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">授课类别</span>
        <select class="holder p14-sele">
            <option>选择授课类别</option>
            <option>流瑜珈</option>
            <option>阴瑜伽</option>
            <option>哈他瑜伽</option>
        </select>
    </div>
</div>

<div class="blackrowgall">
    <div class="row">
        <span class="tt">银行</span>
        <select class="holder p14-sele">
            <option>选择银行</option>
            <option>中国银行</option>
            <option>建设银行</option>
            <option>招商银行</option>
            <option>工商银行</option>
            <option>交通银行</option>
            <option>农业银行</option>
            <option>民生银行</option>
            <option>平安银行</option>
            <option>深圳发展银行</option>
            <option>中信银行</option>
            <option>广发银行</option>
            <option>浦发银行</option>
            <option>光大银行</option>
            <option>华夏银行</option>
            <option>兴业银行</option>
            <option>浙商银行</option>
            <option>广东南粤银行</option>
        </select>
    </div>
    <div class="row">
        <span class="tt">银行卡号</span>
        <input placeholder="请填写正确卡号" value="" type="text" class="holder" />
    </div>
    <div class="row">
        <span class="tt">个人介绍</span>
    </div>
    <div class="row auto">
        <textarea class="fulltxtinput" placeholder="请认真填写个人介绍" style="height:120px;"></textarea>
    </div>
</div>
<div class="clear-15"></div>
<div class="fullbtn">确认提交</div>
<div class="bt-distance"></div>