<div class="p16-xeet">
    以下是您申请成为老师的提交和审核记录
</div>
<div class="p16-tbx">
    <?php foreach ($this->application as $a):?>
        <div class="row">
            <div class="td col1"><?php echo date_format($a->created_at, 'm月d日') ?></div>
            <div class="td">
                <?php if ($a->state == "3") :?>
                        <div class="tt">请被拒绝</div>
                        <div class="reject-reason">
                            您的个人资料填写不完善，请重新填写
                        </div>
                        <a href="/apply/<?php echo $this->user_id ?>" class="fullbtn">重新填写</a>
                <?php else : ?>
                    <div class="tt">审核中</div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="clear-15"></div>
<div class="fullbtn normal cd_hottap" hottap="/me/<?php echo $this->user_id ?>">返回</div>

<div class="bt-distance"></div>
<script type="text/javascript">
    var page_type = 1;
</script>