<div class="relativebackt">
    <a href="#" class="arrc">返回</a>
</div>
<div class="suc-t1">
    <div class="suc-t2"></div>
    <p class="suc-t3">申请提交成功</p>
</div>
<div class="clear-20"></div>
<p class="p05-c02">
    您的申请已经提交成功，我们会尽快审核并回复您结果，请随时留意“申请记录”查看审核进度。
</p>
<div class="clear-30"></div>
<div class="autobtn suc-t6 cd_hottap" hottap="/applyhistory/<?php echo $this->user_id ?>">查看申请记录</div>
<div class="bt-distance"></div>
<script type="text/javascript">
    var page_type = 1;
</script>