<script src="<?php echo $this->jsPath("tools/pic.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/index/change-photo.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/index/change-photo.js"); ?>"></script>
<style>

</style>
<div class="relativebackt">
    <a href="javascript:void(0)" onclick="back()" class="arrc">返回</a>
</div>
<div class="p0x-c0">
    上传头像
</div>
<form role="form" enctype="multipart/form-data"  method="post" >
    <div class="p0x-c1">
        <div class="p0x-c4">
            <div class="p0x-c3">
                <?php if ($this->model->head_pic) :?>
                    <img id="pre-image" src="/photo/image/<?php echo $this->model->head_pic ?>" style="width:100%x; height:100%">
                <?php else :?>
                    <img id="pre-image" src="/img/user.jpg" style="width:100%; height:100%">
                <?php endif; ?>
            </div>
        </div>
        <input type="file" capture="camera" accept="image/*" id="upload-head-pic" name="upload-head-pic" style="left:-200px; width:0px">
        <div class="p0x-c5">请选择图片（小于5M）</div>
        <div class="p0x-c6">
            <button type="button" id="btn-choose" class="p0x-c2">选择图片 ...</button>
        </div>
        <div>
            <button type="submit" id="btn-submit" class="p0x-c2 upload" disabled="disabled">上传</button>
        </div>
    </div>
</form>