<style>

</style>

<div class="p0x-c0">
    上传头像
</div>
<div class="p0x-c1">
    <div class="p0x-c4">
        <div class="p0x-c3">

        </div>
    </div>
    <div class="p0x-c5">请选择图片（小于5M）</div>
    <div class="p0x-c6">
        <button type="button" class="p0x-c2">选择图片 ...</button>
    </div>
    <div>
        <button type="button" class="p0x-c2 upload" disabled="disabled">上传</button>
    </div>
    <div>
        <a href="/me/<?php echo $this->model->id ?>" class="p0x-c2 back">返回</a>
    </div>
</div>