<style>
    body {
        padding-bottom:50px;
    }
</style>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=8TN0gC5Rqo6cec2jroKOkNpE&v=2.0"></script>
<script src="<?php echo $this->jsPath("swipe.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/map.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/index/course-detail.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/teacher.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/teacher.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/index/course-detail.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/index/course-detail.js"); ?>"></script>
<script type="text/javascript">
    // 此处是php代码渲染输出而成，一次性把该导师所有的图片路径都加载至此。
    var imgs_json = [
        <?php $index = 0; ?>
            <?php if (count($this->model->photo) > 0) :?>
                <?php foreach($this->model->photo as $p) :?>
                    <?php if($index > 0) :?>
                        <?php echo "," ?>
                    <?php endif; ?>
                        { url: '/photo/image/<?php
                            try {
                                echo $p->name . $p->type;

                                $index++;
                            }
                            catch (Doctrine\ODM\MongoDB\DocumentNotFoundException $e) {

                            }
                        ?>' }
                <?php endforeach; ?>
            <?php else :?>
                { url: '/img/userdefault.jpg' }
            <?php endif; ?>
    ];
</script>

<div class="fixbackt">
    <a class="arrc" href="/course"></a>
</div>

<!--此段为滑动多图的html部分，写死在这里-->
<div id="cd_mentor_img_slider" class="swipe">
    <div class="swipe-wrap">
        <!--<div class="figure"></div>-->
    </div>
    <!-- 放置索引标签的地方 -->
    <div class="gl">
        <!--<div class="pgitm"></div>-->
    </div>
</div>
<div class="p09-t1">
<?php echo $this->model->name ?>
    <span class="l"></span>
</div>
<div class="p09-t2">
    <?php echo $this->model->description ?>
</div>

<div class="tcfilter-fix" style="position: relative;">
    <div class="nothing-btn loc-bt cd-slideoutbtn" rel="#pp-change-loc">
        <span id="address-view">皇御苑</span>
        <img src="/img/arr-d.png" width="12">
    </div>
    <div class="nothing-btn sort-bt">
        <i class="ico"></i>
    </div>
    <div class="switcher">
        <div style="text-align:center;">
            推荐老师
        </div>
        <div class="comok-sp"></div>
    </div>

    <div class="tcfilter-sort">
        <div class="wp">
            <p class="p1">请选择排序方式</p>
            <div>
                <button class="itmbtn selected" sort="teacher_score" type="button">评分高</button>
                <button class="itmbtn" sort="teacher_count" type="button">授课多</button>
            </div>
        </div>
    </div>

<!--    <div class="tcfilter-filter">-->
<!--        <div class="wp">-->
<!--            <p class="p1">选择区</p>-->
<!--            <div>-->
<!--                --><?php //foreach ($this->region as $r):?>
<!--                    <button class="itmbtn" type="button" id="--><?php //echo $r->id?><!--">--><?php //echo $r->name ?><!--</button>-->
<!--                --><?php //endforeach;?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>

<div class="tcfilter-container" style="padding-top:0;">

</div>


<!--<div class="list-end-loadmore">-->
<!--    <span>正在加载更多，请稍候 ...</span>-->
<!--</div>-->

<div id="teacher-item" style="display: none">
    <div class="teacher-itm">
        <div class="pad-15">
            <div class="user-intro cd_hottap" hottap="">
                <div class="li">
                    <img class="user-intro-img" src="/img/user01.jpg" />
                </div>
                <div class="li">
                    <div class="user-intro-txt"><span class="teacher-name"></span><span class="teacher-score"> · <span class="this-teacher-score"></span>分</span></div>
                    <div class="user-intro-skill"></div>
                </div>
                <div class="user-intro-tag">
                    <span class="t1">￥<span class="price"></span></span>
                    <span class="t2">每小时</span>
                </div>
            </div>
        </div>
        <div>
            <img src="" class="teacher-img-big cd_hottap" hottap="" />
        </div>
    </div>
    <div class="teacher-none">
        <div class="pad-15">
            <div class="user-intro cd_hottap" hottap="">
                <div class="li">
                    <div class="user-intro-txt"><span class="teacher-name"></span</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="slidepopup cd-slidepopup" id="pp-change-loc">
    <div class="tt">选择授课地址<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="address-list" style="position:absolute;left:0;right:0;top:60px;bottom:0;overflow-y:auto">
        <div style="padding:10px 15px 0 15px;">
            <input id="edit-addr" placeholder="请输入详细地址" type="text" class="fulltxtinput" />
            <button id="btn-addr-query" class="sendvalcodbt">查询</button>
        </div>
        <div class="clear-15"></div>
        <div id="addr-list" class="loc-ddl-bd">
        </div>
        <div class="clear-15"></div>
    </div>
    <div class="clear-15"></div>
</div>
<div id="div-addr-node" style="display: none">
    <div class="loc-ddl-itm">
        <p class="t1"></p>
        <div class="t2"></div>
        <i class="ico"></i>
    </div>
</div>
<script type="text/javascript">
    var lesson_id = '<?php echo $this->model->id ?>';
    var page_type = 0;
    var lat = false;
    var lng = false;

    $('document').ready(function() {
        if (imgs_json.length) {
            // 根据imgs_json的长度和内容循环加载图片
            $.each(imgs_json, function() {
                var new_img = $('<div>').addClass('figure');
                new_img.css('background-image', 'url(' + this.url + ')');
                $('#cd_mentor_img_slider .swipe-wrap').append(new_img);
            });
            // 初始化swipe
            var slider = Swipe(document.getElementById('cd_mentor_img_slider'), {
                startSlide: 0,
                speed: 400,
                auto: false,
                continuous: false,
                disableScroll: false,
                stopPropagation: false,
                callback: function(index, elem) {},
                transitionEnd: function(index, elem) {
                    $('.gl .pgitm.selected').removeClass('selected');
                    $('.gl .pgitm[index="' + index + '"]').addClass('selected');
                }
            });
            // 初始化pager
            var n = slider.getNumSlides();
            for (var i = 0; i < n; i++) {
                var new_pager = $('<div>').addClass('pgitm').attr('index', i);
                if(i === 0) {
                    new_pager.addClass('selected');
                }
                $('.swipe .gl').append(new_pager);
            }
        }
    });
</script>