<div class="tcfilter-fix">
    <!--<div class="nothing-btn loc-bt">
        <i class="ico"></i>
    </div>
    <div class="nothing-btn sort-bt">
        <i class="ico"></i>
    </div>-->
    <div class="switcher">
        <div class="nothing-btn comok lt cd_hottap" hottap="/">
            <div class="wp">
                <span class="txt">老师</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="nothing-btn comok rt selected cd_hottap" hottap="/course">
            <div class="wp">
                <span class="txt">课程</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="comok-sp"></div>
    </div>

    <div class="tcfilter-sort">
        <div class="wp">
            <p class="p1">请选择排序方式</p>
            <div>
                <button class="itmbtn selected" type="button">授课多</button>
                <button class="itmbtn" type="button">评价高</button>
            </div>
        </div>
    </div>

    <div class="tcfilter-filter">
        <div class="wp">
            <p class="p1">选择区</p>
            <div>
                <button class="itmbtn selected" type="button">罗湖</button>
                <button class="itmbtn" type="button">福田</button>
                <button class="itmbtn" type="button">南山</button>
                <button class="itmbtn" type="button">宝安</button>
                <button class="itmbtn" type="button">盐田</button>
                <button class="itmbtn" type="button">龙岗</button>
                <button class="itmbtn" type="button">光明</button>
                <button class="itmbtn" type="button">坪山</button>
            </div>
        </div>
    </div>
</div>

<div class="menu-fix">
    <div class="menu-fix-itm cd_hottap selected" hottap="/">预约老师</div>
    <div class="menu-fix-itm cd_hottap" hottap="/me">我</div>
</div>

<style>
    .loc-bt, .sort-bt {
        display:none;
    }
</style>
<div class="tcfilter-container padt50">
    <div class="cc-itm cd_hottap" hottap='/coursedetail' style="background-image:url(img/ts1.jpg)">
        <div class="cv"></div>
        <div class="tt">大自然瑜伽</div>
        <div class="stt">一句话对于大自然瑜伽的简介</div>
    </div>

    <div class="cc-itm" style="background-image:url(img/ts2.jpg)">
        <div class="cv"></div>
        <div class="tt">大自然瑜伽</div>
        <div class="stt">一句话对于大自然瑜伽的简介</div>
    </div>

    <div class="cc-itm" style="background-image:url(img/ts3.jpg)">
        <div class="cv"></div>
        <div class="tt">大自然瑜伽</div>
        <div class="stt">一句话对于大自然瑜伽的简介</div>
    </div>

    <div class="cc-itm" style="background-image:url(img/ts4.jpg)">
        <div class="cv"></div>
        <div class="tt">大自然瑜伽</div>
        <div class="stt">一句话对于大自然瑜伽的简介</div>
    </div>

    <div class="cc-itm" style="background-image:url(img/ts5.jpg)">
        <div class="cv"></div>
        <div class="tt">大自然瑜伽</div>
        <div class="stt">一句话对于大自然瑜伽的简介</div>
    </div>
</div>

<div class="list-end-loadmore">
    <span>正在加载更多，请稍候 ...</span>
</div>