<style>
    body {
        padding-bottom:70px;
    }
</style>
<script src="<?php echo $this->jsPath("controller/index/course.js"); ?>"></script>
<div class="fixbackt">
    <a class="arrc" href="/"></a>
</div>
<div class="tcfilter-fix">
    <!--<div class="nothing-btn loc-bt">
        <i class="ico"></i>
    </div>
    <div class="nothing-btn sort-bt">
        <i class="ico"></i>
    </div>-->
    <div class="switcher">
        <div class="nothing-btn comok lt cd_hottap" hottap="/">
            <div class="wp">
                <span class="txt">老师</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="nothing-btn comok rt selected cd_hottap" hottap="/course">
            <div class="wp">
                <span class="txt">课程</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="comok-sp"></div>
    </div>

    <div class="tcfilter-sort">
        <div class="wp">
            <p class="p1">请选择排序方式</p>
            <div>
                <button class="itmbtn selected" type="button">授课多</button>
                <button class="itmbtn" type="button">评价高</button>
            </div>
        </div>
    </div>

<!--    <div class="tcfilter-filter">-->
<!--        <div class="wp">-->
<!--            <p class="p1">选择区</p>-->
<!--            <div>-->
<!--                --><?php //foreach ($this->region as $r):?>
<!--                    <button class="itmbtn" type="button" id="--><?php //echo $r->id?><!--">--><?php //echo $r->name ?><!--</button>-->
<!--                --><?php //endforeach;?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>

<div class="menu-fix">
    <div class="menu-fix-itm cd_hottap selected" hottap="/">预约老师</div>
    <div id="to-me" class="menu-fix-itm cd_hottap" hottap="/me">我</div>
</div>

<style>
    .loc-bt, .sort-bt {
        display:none;
    }
    .fixbackt {
        display:none;
    }
</style>
<div class="tcfilter-container padt50">
    <?php foreach($this->lessons as $lesson):?>
        <div class="cc-itm cd_hottap" hottap='/coursedetail/<?php echo $lesson->id ?>'
            <?php  if ($lesson->photo && count($lesson->photo) > 0) :?>
                style=" background-image:url(/photo/image/<?php echo $lesson->photo[0]->name . $lesson->photo[0]->type?>)"
            <?php endif; ?>
            >
            <div class="cv"></div>
            <div class="tt"><?php echo $lesson->name ?></div>
            <div class="stt"><?php echo $lesson->description ?></div>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    var page_type = 0;
</script>
<!--<div class="list-end-loadmore">-->
<!--    <span>正在加载更多，请稍候 ...</span>-->
<!--</div>-->