<script src="<?php echo $this->jsPath("swipe.js"); ?>"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=8TN0gC5Rqo6cec2jroKOkNpE&v=2.0"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/index/home.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/index/home.js"); ?>"></script>
<div style="height:60px;background:url(/img/za-bg.jpg);line-height:60px;font-weight:bold;text-align:center;color:#FFF;background-size: cover">
<img src="/img/txtlogo.png" style="width:120px;margin-top:-2px;"/>
    <a href="#" id="to-me"></a>
</div>
<!--此段为滑动多图的html部分，写死在这里-->
<div id="cd_mentor_img_slider" class="swipe homex">
    <div class="swipe-wrap">
        <!--<div class="figure"></div>-->
    </div>
    <!-- 放置索引标签的地方 -->
    <div class="gl">
        <!--<div class="pgitm"></div>-->
    </div>
</div>

<style>
    .iueici {
        padding-top:20px;
    }
    .iueici .itm {
        display:block;
        width:50%;
        float:left;
        text-align: center;
    }
    .iueici .itm .wp {
        margin:0 5px 10px 10px;
        display:block;
        height:120px;
        background:#ff9ba7;
        color:#FFF;
        line-height: 120px;
        background-position: center center;
        background-repeat:no-repeat;
        background-size: cover;
    }
    .iueici .itm.i01 .wp {
        background-image:url(/img/home/jpkc.jpg);
    }
    .iueici .itm.i02 .wp {
        background-image:url(/img/home/gyk.jpg);
    }
    .iueici .itm.i03 .wp {
        background-image:url(/img/home/yjsl.jpg);
    }
    .iueici .itm.i04 .wp {
        background-image:url(/img/home/yyds.jpg);
    }

    .iueici .itm:nth-child(even) .wp {
        margin-right:10px;
        margin-left:5px;
    }

    .homex .swipe-wrap > .figure {
        height:270px;
    }
</style>
<div class="iueici">
    <div class="itm i01">
        <a href="/course" class="wp"></a>
    </div>
    <div class="itm i02">
        <a href="#" class="wp"></a>
    </div>
    <div class="itm i03">
        <a href="#" class="wp"></a>
    </div>
    <div class="itm i04">
        <a href="#" class="wp"></a>
    </div>
</div>

<div class="tcfilter-container">

</div>

<script type="text/javascript">
    var page_type = 0;
    var user_id = localStorage.getItem('user_id');
    var usertype = localStorage.getItem('usertype');

    var lat = false;
    var lng = false;



    // 此处是php代码渲染输出而成，一次性把该导师所有的图片路径都加载至此。
    var imgs_json = [{
        url: '/img/home/banner-01.jpg', link: '#'
    }, {
        url: '/img/home/banner-02.jpg', link: '#'
    }, {
        url: '/img/home/banner03.jpg', link: '#'
    }];


    if (imgs_json.length) {
        // 根据imgs_json的长度和内容循环加载图片
        $.each(imgs_json, function() {
            var new_img = $('<a>').addClass('figure').css('display', 'block').attr('href', this.link);
            new_img.css('background-image', 'url(' + this.url + ')');
            $('#cd_mentor_img_slider .swipe-wrap').append(new_img);
        });
        // 初始化swipe
        var slider = Swipe(document.getElementById('cd_mentor_img_slider'), {
            startSlide: 0,
            speed: 400,
            auto: false,
            continuous: false,
            disableScroll: false,
            stopPropagation: false,
            callback: function(index, elem) {},
            transitionEnd: function(index, elem) {
                $('.gl .pgitm.selected').removeClass('selected');
                $('.gl .pgitm[index="' + index + '"]').addClass('selected');
            }
        });
        // 初始化pager
        var n = slider.getNumSlides();
        for (var i = 0; i < n; i++) {
            var new_pager = $('<div>').addClass('pgitm').attr('index', i);
            if(i === 0) {
                new_pager.addClass('selected');
            }
            $('.swipe .gl').append(new_pager);
        }
    }

    $(document).ready(function(){
        // 大按钮的高度设置成功
        var w = $('.iueici .itm .wp').width();
        $('.iueici .itm .wp').height(w);
        //var regions = $(".tcfilter-filter").find(".itmbtn");
        //
        //$(regions[1]).addClass("selected");
        //55f3d0607406f74f758b4624 滕燕
        //55f29c427406f750758b45db	彭彩红
        //56049fad7406f7536f8b45fb 傅丽君
        //5604a6677406f7007f8b4568	温利华
        //55f682737406f74f758b4646	刘郎平
        //55ed73fc7406f7ac7f8b4567 戴炳锋
//服务器测试：55ebe5c67406f7ba678b4573
//测试用:55caf092d53de42d048b456c//55ced8b3d53de429048b456b//55f2d8bfd53de415048b4569//56097231d53de428048b4569
//        localStorage.setItem('user_id', '56097231d53de428048b4569');
    });
</script>