<style>
    body {
        padding-bottom:70px;
    }
</style>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=8TN0gC5Rqo6cec2jroKOkNpE&v=2.0"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/map.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/index/index.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/teacher.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/teacher.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/index/index.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/index/index.js"); ?>"></script>
<div class="tcfilter-fix">
    <div class="nothing-btn loc-bt cd-slideoutbtn" rel="#pp-change-loc">
        <span id="address-view"></span>
        <img src="/img/arr-d.png" width="12">
    </div>
    <div class="nothing-btn sort-bt">
        <i class="ico"></i>
    </div>
    <div class="switcher">
        <div class="nothing-btn comok lt selected cd_hottap" hottap="/teacherdate">
            <div class="wp">
                <span class="txt">老师</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="nothing-btn comok rt cd_hottap" hottap="/course">
            <div class="wp">
                <span class="txt">课程</span>
                <span class="l"></span>
            </div>
        </div>
        <div class="comok-sp"></div>
    </div>

    <div class="tcfilter-sort">
        <div class="wp">
            <p class="p1">请选择排序方式</p>
            <div>
                <button class="itmbtn selected" sort="teacher_score" type="button">评分高</button>
                <button class="itmbtn" sort="teacher_count" type="button">授课多</button>
            </div>
        </div>
    </div>

<!--    <div class="tcfilter-filter">-->
<!--        <div class="wp">-->
<!--            <p class="p1">选择区</p>-->
<!--            <div>-->
<!--                --><?php //foreach ($this->region as $r):?>
<!--                    <button class="itmbtn" type="button" id="--><?php //echo $r->id?><!--">--><?php //echo $r->name ?><!--</button>-->
<!--                --><?php //endforeach;?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>



<div class="tcfilter-container">

</div>

<!--<div class="list-end-loadmore">-->
<!--    <span>正在加载更多，请稍候 ...</span>-->
<!--</div>-->
<div class="slidepopup cd-slidepopup" id="pp-change-loc">
    <div class="tt">筛选老师<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div id="search_name">
        <div class="mbttk">搜索老师姓名</div>
        <div class="loc-search-wp">
            <input id="edit-teacher-name" placeholder="请输入老师姓名" type="text" class="fulltxtinput loc-search-txt" />
            <button id="btn-teacher-query" class="sendvalcodbt loc-search-submitbtn rbdi">查询</button>
        </div>
    </div>
    <div class="address-list golsaddr">
        <div class="mbttk">选择授课地址</div>
        <div class="loc-search-wp">
            <input id="edit-addr" placeholder="请输入详细地址" type="text" class="fulltxtinput loc-search-txt" />
            <button id="btn-addr-query" class="sendvalcodbt loc-search-submitbtn">查询</button>
            <button id="btn-get-loc" class="sendvalcodbt loc-search-getnow">当前地址</button>
        </div>
        <div class="clear-15"></div>
        <div id="addr-list" class="loc-ddl-bd">
        </div>
        <div class="clear-15"></div>
    </div>
    <div class="clear-15"></div>
</div>
<div id="teacher-item" style="display: none">
    <div class="teacher-itm">
        <div class="pad-15">

            <div class="teacher-img-big cd_hottap" hottap="" ></div>
            <div class="user-intro cd_hottap" hottap="">

                <div class="li">
                    <div class="user-intro-txt"><span class="teacher-name"></span><span class="teacher-score"> <span class="this-teacher-score"></span>分</span></div>
                    <div class="user-intro-skill"></div>
                </div>
                <div class="user-intro-tag">
                    <span class="t1">￥<span class="price"></span></span>
                    <span class="t2">每小时</span>
                </div>
            </div>
        </div>
    </div>
    <div class="teacher-none">
        <div class="pad-15">
            <div class="user-intro cd_hottap" hottap="">
                <div class="li">
                    <div class="user-intro-txt"><span class="teacher-name"></span</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="div-addr-node" style="display: none">
    <div class="loc-ddl-itm">
        <p class="t1"></p>
        <div class="t2"></div>
        <i class="ico"></i>
    </div>
</div>
<script type="text/javascript">
    var page_type = 0;
    var user_id = localStorage.getItem('user_id');
    var usertype = localStorage.getItem('usertype');

    var lat = false;
    var lng = false;
</script>