<div class="suc-t1">
    <div class="suc-t2"></div>
    <p class="suc-t3">下课啦！</p>
</div>
<div class="p05-c02">
    <?php echo $this->model->teacher->name ?>老师，非常感谢您辛勤的付出，本次授课已经结束，我们会鼓励学员为您的表现做出一个客观的评价，本次课酬即将进入到您的余额中，谢谢。
</div>
<div class="clear-20"></div>

<div class="clear-30"></div>
<div class="fullbtn normal cd_hottap" hottap="/me/<?php echo $this->model->teacher->id ?>">返回</div>
<div class="bt-distance"></div>
