<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>我</title>

    <!-- Bootstrap -->
    <link href="css/global.css" rel="stylesheet">
</head>
<body ontouchstart="">
<div class="menu-fix">
    <div class="menu-fix-itm cd_hottap" hottap="/">预约老师</div>
    <div class="menu-fix-itm cd_hottap selected" hottap="/me">我</div>
</div>
<div class="p10-head-warning" id="didntsettel">
    您还没有设置手机号码，前往设置
</div>
<div class="p10-t02">
    <img src="img/user04.jpg" class="usrgmi" />
    <div class="p10-t03">Jeans chan</div>
</div>

<div class="blackrowgall nmt">
    <div class="row actbtn cd-slideoutbtn" rel="#pp-change-name">
        <span class="tt">真实姓名</span>
        <div class="holder arr">
            <span>张三丰</span>
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn cd-slideoutbtn" id="pp-change-tel-btn" rel="#pp-change-tel">
        <span class="tt">手机</span>
        <div class="holder arr">
            <span>18923833647</span>
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn cd-slideoutbtn my-intro-trigger" id="pp-my-intro-btn" rel="#pp-my-intro">
        <span class="tt">个人介绍</span>
        <div class="holder arr">
            <span class="lab-txt">我是一名来自山东的自愿者</span>
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn cd-slideoutbtn" rel="#pp-change-years">
        <span class="tt">练习瑜伽</span>
        <div class="holder arr">
            <span>3年</span>
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
</div>

<div class="blackrowgall">
    <div class="row actbtn">
        <span class="tt">我的订单</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">优惠券</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">我的消息</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
</div>

<div class="blackrowgall tran unclickable">
    <div class="row actbtn">
        <span class="tt">我的总收入</span>
        <div class="holder">
            <span class="gold">￥7889</span>
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">未提现金额</span>
        <div class="holder">
            <span class="gold">￥209</span>
        </div>
    </div>
</div>

<div class="blackrowgall">
    <div class="row actbtn">
        <span class="tt">日程表</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">我的授课</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn">
        <span class="tt">我的课程</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
</div>

<div class="blackrowgall">
    <div class="row actbtn cd_hottap" hottap="/apply">
        <span class="tt">申请成为老师</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn cd_hottap" hottap="/applyhistory">
        <span class="tt">查看申请记录</span>
        <div class="holder arr">
            <img src="img/arr-r.png" class="icoin" />
        </div>
    </div>
</div>

<div class="bt-distance"></div>


<div class="slidepopup cd-slidepopup" id="pp-change-name">
    <div class="tt">更改真实姓名<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <input placeholder="请填写" type="text" maxlength="11" value="张三丰" class="fulltxtinput" />
        </div>
    </div>
    <div class="clear-15"></div>
    <div class="fullbtn">
        确认
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-change-years">
    <div class="tt">更改瑜伽年限<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <input placeholder="请填写练习瑜伽的年限" type="tel" maxlength="11" value="3" class="fulltxtinput" />
        </div>
    </div>
    <div class="clear-15"></div>
    <div class="fullbtn">
        确认
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-my-intro">
    <div class="tt">更改个人介绍<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row auto">
            <textarea class="fulltxtinput" placeholder="请填写">我是一名来自山东的自愿者，有着5年的瑜家训练历史。</textarea>
        </div>
    </div>
    <div class="clear-15"></div>
    <div class="fullbtn">
        确认
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-change-tel">
    <div class="tt">更改电话号码<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <input placeholder="请填写手机号码" type="tel" maxlength="11" value="18923833647" class="fulltxtinput" />
            <button class="sendvalcodbt">发送验证码</button>
        </div>
        <div class="row">
            <input placeholder="验证码" type="tel" maxlength="11" class="fulltxtinput" />
        </div>
    </div>
    <div class="clear-15"></div>
    <div class="fullbtn">
        确认
    </div>
</div>

<script type="text/javascript" src="js/jquery-1.11.0.js"></script>
<script type="text/javascript" src="js/jquery-mobile.js"></script>
<script type="text/javascript" src="js/global.js"></script>
<script type="text/javascript" src="js/swipe.js"></script>
<script>
    $('document').ready(function() {
        $('#didntsettel').tap(function(){
            $('#pp-change-tel-btn').tap();
        });
    });
</script>
</body>

</html>