<script src="<?php echo $this->jsPath("controller/index/my-order.js"); ?>"></script>
<div class="p16-xeet">
    找到<span id="order-num"><?php echo $this->count ?></span>条记录
</div>

<div class="blackrowgall nmt">
    <?php foreach ($this->order_list as $order):?>
        <div class="row actbtn cd_hottap" hottap="/order/detail/<?php echo $order->id ?>">
            <div class="tt"><span class="user-name"><?php echo $order->teacher->name ?></span><span class="p17-t01 rundate-time"><?php
                    $tmp_date = explode("-", $order->rundate);

                    $tmp_text = "";

                    if (substr($tmp_date[1], 0, 1) == "0") {
                        $tmp_text = substr($tmp_date[1], 1, 1) . "月";
                    }
                    else {
                        $tmp_text = $tmp_date[1] . "月";
                    }

                    if (substr($tmp_date[2], 0, 1) == "0") {
                        $tmp_text = $tmp_text . substr($tmp_date[2], 1, 1) . "日";
                    }
                    else {
                        $tmp_text = $tmp_text . $tmp_date[2] . "日";
                    }

                    echo  $tmp_text;
                    ?> <?php echo explode("|",$order->time)[0] ?></span></span></div>
            <div class="holder arr">
                <img src="/img/arr-r.png" class="icoin" />
            </div>
             <span class="status-for-order-sm status <?php
                if ($order->state == 50) {
                    echo "completed";
                }
                else {
                    echo "pending";
                }
             ?>">
             <?php
                 switch ($order->state) {
                     case "0":{
                         echo "待付款"; break;
                     }
                     case "10":{
                         echo "待付款"; break;
                     }
                     case "20":{
                         echo "已付款"; break;
                     }
                     case "30":{
                         echo "授课中"; break;
                     }
                     case "40":{
                         echo "等待评价"; break;
                     }
                     case "50":{
                         echo "完成"; break;
                     }
                 }
             ?></span>
        </div>
    <?php endforeach;?>
</div>

<div class="clear-15"></div>
<div id="to-me" class="fullbtn normal cd_hottap" hottap="">返回</div>
<div class="bt-distance"></div>
<!--completed pending -->
<div id="order-node" style="display: none">
</div>
