<div class="suc-t1">
    <div class="suc-t2"></div>
    <p class="suc-t3">评价提交成功</p>
    <div class="suc-t4">
        您的每一次评分对我们都是非常宝贵的回馈我们将持续为您提供更好的课程和服务
    </div>
</div>
<div class="clear-30"></div>
<div class="autobtn suc-t6 cd_hottap" hottap="/">赶紧预约下一次课吧</div>
<div class="bt-distance"></div>
<script type="text/javascript">
    var page_type = 1;

    $('document').ready(function() {

    });
</script>
