<script src="<?php echo $this->jsPath("swipe.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/sms.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/tools.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/index/reg-user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/index/reg-user.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/index/reg-user.js"); ?>"></script>
<div class="p10-head-warning" id="didntsettel">
    请输入用户信息进行注册
</div>

<div class="p10-t02">
    <img src="<?php echo $this->model->headimgurl ?>" style="width:100px" class="usrgmi" />
    <div class="p10-t03"><?php echo $this->model->nickname ?></div>
</div>

<div class="blackrowgall nmt">
    <div class="row actbtn cd-slideoutbtn" rel="#pp-change-name">
        <span class="tt">真实姓名</span>
        <div class="holder arr">
            <span id="my-name"><?php echo $this->model->name ?></span>
            <img src="/img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row actbtn cd-slideoutbtn" id="pp-change-tel-btn" rel="#pp-change-tel">
        <span class="tt">手机</span>
        <div class="holder arr">
            <span id="my-phone"><?php echo $this->model->phone ?></span>
            <img src="/img/arr-r.png" class="icoin" />
        </div>
    </div>
    <div class="row cd-slideoutbtn" id="pp-change-code-btn" rel="#pp-change-code">
        <span class="tt">身份证号码</span>
        <div class="holder arr">
            <span id="my-code"><?php echo $this->model->code ?></span>
            <img src="/img/arr-r.png" class="icoin" />
        </div>
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-change-name">
    <div class="tt">更改真实姓名<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <input placeholder="请填写" id="user-name" type="text" maxlength="11" value="<?php echo $this->model->name ?>" class="fulltxtinput" />
        </div>
    </div>
    <div class="clear-15"></div>
    <div id="btn-accept-name" class="fullbtn">
        确认
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-change-tel">
    <div class="tt">更改电话号码<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <input placeholder="请填写手机号码"  id="phone-num" type="tel" maxlength="11" value="<?php echo $this->model->phone ?>" class="fulltxtinput" />
            <button id="send-code" class="sendvalcodbt">发送验证码</button>
        </div>
        <div class="row">
            <input placeholder="验证码" id="phone-code"  type="tel" maxlength="11" class="fulltxtinput" />
        </div>
    </div>
    <div class="clear-15"></div>
    <div id="valid-phone-code"  class="fullbtn">
        确认
    </div>
</div>

<div class="slidepopup cd-slidepopup" id="pp-change-code">
    <div class="tt">更改身份证号码<span class="back rt cd-slidepopupback"><i class="ico"></i></span></div>
    <div class="blackrowgall">
        <div class="row">
            <div class="holder">
                <input placeholder="填写正确身份证号码" id="code" name="code" maxlength="18" value="<?php echo $this->model->code ?>" type="text" class="holder" />
            </div>
        </div>
    </div>
    <div class="clear-15"></div>
    <div id="valid-code-code"  class="fullbtn">
        确认
    </div>
</div>

<div class="clear-15"></div>
<button id="submit-reg" type="button" class="fullbtn" style="height: 50px; font-size: medium">确认提交</button>
<script type="text/javascript">
    var user_id = '<?php echo $this->model->id ?>';
    var page_type = 0;
</script>