
<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
<div class="col-md-8">
<form role="form" enctype="multipart/form-data"  method="post" >
<input type="hidden" id="wxid" name="wxid">
    <div class="form-group">
        <label>昵称：</label>
        <input type="text" class="form-control" id="nickname" name="nickname" data-toggle="popover" value="<?php echo $this->model->nickname ?>" required="required" oninvalid="setCustomValidity('必须填写老师姓名!');" oninput="setCustomValidity('');">
    </div>
<div class="form-group">
    <label>姓名：</label>
    <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $this->model->name ?>" oninput="setCustomValidity('');">
</div>
<div class="form-group">
    <label>优惠卷金额：</label>
    <input type="number" class="form-control" id="amount" name="amount" data-toggle="popover" value=""  oninput="setCustomValidity('');" required="required" oninvalid="setCustomValidity('必须填写金额!');>
</div>
<div class="clear-10"></div>
<button type="submit" id="save-btn"  class="btn btn-default">确认提交</button>
</form>
</div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>