
<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>用户昵称：</label>
                <input type="text" class="form-control" id="nickname" name="nickname" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>用户性别：</label>
                <input type="text" class="form-control" id="sex" name="sex" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>用户id：</label>
                <input type="text" class="form-control" id="openid" name="openid" data-toggle="popover" value="">
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>