<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>老师管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-teacher-list-home') ?>" role="button">老师列表 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-teacher-create') ?>" role="button">添加老师 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-teacher-application') ?>" role="button">老师申请列表 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>用户管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-customer-list-home') ?>" role="button">用户列表 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-customer-frozen-list-home') ?>" role="button">冻结用户列表 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>授课历史</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-order-list-home') ?>" role="button">授课列表 »</a></p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>课程管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-lesson-list-home') ?>" role="button">查看所有课程 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-lesson-create') ?>" role="button">添加课程 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>区域管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-region-list-home') ?>" role="button">课程区域 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-region-create') ?>" role="button">添加区域 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>瑜伽分类管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-list-home') ?>" role="button">瑜伽分类列表 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-create') ?>" role="button">添加瑜伽分类 »</a></p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>图片管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-list-home') ?>" role="button">查看所有图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-upload') ?>" role="button">上传图片 »</a></p>
<!--            <p><a class="btn btn-default" href="--><?php //echo $this->url(array(), 'manage-phototype-list-home') ?><!--" role="button">管理图片分类 »</a></p>-->
        </div>
    </div>

    <div class="col-md-4">
        <div class="intlbd">
            <h2>工时管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-work-list-home') ?>" role="button">查看工时 »</a></p>
        </div>
    </div>
</div>
<style>
    .row {
        margin-bottom:30px;
    }
</style>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>
