
<style>
</style>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("tools/pic.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/manage/teacher-create.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/customer.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/customer.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/manage/teacher-create.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/manage/teacher-create.js"); ?>"></script>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label>微信ID：</label>
            <span class="span-openid">暂未微信登录及指定用户</span>
            <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#customer-list">绑定微信用户</button>
        </div>
        <div class="form-group">
            <label>微信昵称：</label>
            <span class="span-nickname">暂未微信登录及指定用户</span>
        </div>
<!--        <div class="form-group">-->
<!--            <label>性别：</label>-->
<!--            <span class="span-sex">暂未微信登录及指定用户</span>-->
<!--        </div>-->
    </div>
    <div class="col-md-8">
        <form role="form" enctype="multipart/form-data" method="post">
            <input type="hidden" id="wxid" name="wxid">
            <input type="hidden" id="wxname" name="wxname">
<!--            <input type="hidden" id="wxsex" name="wxsex">-->
            <input type="hidden" id="wxcity" name="wxcity">
            <input type="hidden" id="wxheadimgurl" name="wxheadimgurl">
            <div class="form-group">
                <label>头像：</label>
                <img id="pre-image">
                <input type="file" capture="camera" accept="image/*" id="upload-head-pic" name="upload-head-pic">
            </div>
            <div class="form-group">
                <label>姓名：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="" required="required" oninvalid="setCustomValidity('必须填写老师姓名!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>性别：</label>
                <select id="sex" name="sex">
                    <option value="1">男</option>
                    <option value="2">女</option>
                </select>
            </div>
            <div class="form-group">
                <label>出生日期：</label>
                <input type="date" class="form-control" id="birthday" name="birthday" data-toggle="popover" value="1985-01-01"  oninput="setCustomValidity('');"> <!--required="required" oninvalid="setCustomValidity('必须填写出生日期!');"-->
            </div>
            <div class="form-group">
                <label>籍贯：</label>
                <input type="text" class="form-control" id="place" name="place" data-toggle="popover" value="" oninput="setCustomValidity('');"><!-- required="required" oninvalid="setCustomValidity('必须填写籍贯!');" -->
            </div>
            <div class="form-group">
                <label>学历：</label>
                <input type="text" class="form-control" id="educational" name="educational" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写学历!');"-->
            </div>
<!--            <div class="form-group">-->
<!--                <label>证书：</label>-->
<!--<!--                <input type="text" class="form-control" id="certificate" name="certificate" data-toggle="popover" value="" required="required" oninvalid="setCustomValidity('必须填写证书!');" oninput="setCustomValidity('');">-->-->
<!--                <img id="pre-certificate-image">-->
<!--                <input type="file" capture="camera" accept="image/*" id="upload-certificate-pic" name="upload-certificate-pic">-->
<!--            </div>-->
            <div class="form-group">
                <label>联系电话：</label>
                <input type="number" class="form-control" id="phone" name="phone" maxlength="11" data-toggle="popover" value="" required="required" oninvalid="setCustomValidity('必须填写联系电话!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>身份证号：</label>
                <input type="text" class="form-control" id="code" name="code" maxlength="18" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写身份证号!');"-->
            </div>
            <div class="form-group">
                <label>电子邮箱：</label>
                <input type="email" class="form-control" id="email" name="email" data-toggle="popover" value="" oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写电子邮箱!');" -->
            </div>
            <div class="form-group">
                <label>微信：</label>
                <input type="text" class="form-control" id="wechat" name="wechat" data-toggle="popover" value="" oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写微信号!');" -->
            </div>
            <div class="form-group">
                <label>QQ：</label>
                <input type="number" class="form-control" id="qq" name="qq" maxlength="15" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写QQ号!');"-->
            </div>
            <div class="form-group">
                <label>教学年数：</label>
                <input type="number" class="form-control" id="years" name="years" maxlength="15" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写教学年数!');"-->
            </div>
            <div class="form-group">
                <label>授课价格(小时)：</label>
                <input type="number" class="form-control money" id="price" name="price" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写授课价格!');"-->
            </div>
            <div class="form-group">
                <label>所在城市：</label>
                <input type="text" class="form-control" id="location" name="location" data-toggle="popover" value=""  oninput="setCustomValidity('');"><!--required="required" oninvalid="setCustomValidity('必须填写所在城市!');"-->
            </div>
            <div class="form-group">
                <label>授课区域：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->regions as $region): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $region->id ?>" type="checkbox" name="region[]" value="<?php echo $region->id ?>"  /> <label class="marginright10px" for="<?php echo $region->id ?>"><?php echo $region->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->regions) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-region-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以授课区域， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>擅长瑜伽：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->categorys as $category): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $category->id ?>" type="checkbox" name="category[]" value="<?php echo $category->id ?>"/> <label class="marginright10px" for="<?php echo $category->id ?>"><?php echo $category->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->categorys) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-category-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>授课类型：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->lessons as $lesson): ?>
                    <div style="float:left" >
                        <input id="<?php echo $lesson->id ?>" type="checkbox" name="lesson[]" value="<?php echo $lesson->id ?>"
                            <?php
                            foreach ($this->model->lesson as $p) {
                                if ($lesson->id == $p->id) {
                                    echo "checked='checked'";

                                    break;
                                }
                            }
                            ?>/> <label class="marginright10px" for="<?php echo $lesson->id ?>"><?php echo $lesson->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->lessons) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-lesson-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽课程可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>银行：</label>
                <input type="text" class="form-control" id="bank" name="bank" data-toggle="popover" value="" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>帐号：</label>
                <input type="number" class="form-control" id="bank_code" name="bank_code" data-toggle="popover" value="" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>老师照片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div class="form-group">
                <label>简介：</label>
                <textarea row="10" class="form-control" id="description" name="description"></textarea>
            </div>
            <div class="form-group">
                <label>授课经历：</label>
                <textarea row="10" class="form-control" id="experience" name="experience"></textarea>
            </div>
            <div class="form-group">
                <div class="col-md-8">
                    <div class="btb">
                        <button type="button" id="btn-skill-add" class="btn btn-default" href="javascript:void(0)">新建评估分数</button>
                    </div>
                    <div id="skill-list" class="col-md-8">
                    </div>
                </div>
            </div>
            <input type="hidden" id="skills" name="skills">
            <div class="clear-10"></div>
            <button type="submit" id="save-btn"  class="btn btn-default">确认提交</button>
        </form>
    </div>
    <div id="skill-model" style="display: none">
        <div class="form-group">
            <label>评估名称：</label>
            <input type="text" class="skill-name" data-toggle="popover" value="">
            <label>评估分数：</label>
            <input type="text" class="skill-value" data-toggle="popover" value="">
            <button class="btn-skill-remove" type="button">删除评估</button>
        </div>
    </div>
    <div class="modal fade" id="customer-list" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        用户列表
                    </h4>
                </div>
                <div class="modal-body">
                    <label>微信昵称：</label>
                    <input type="text" id="wx-name" data-toggle="popover" value=""><button type="button" id="bang-customer" >查询</button>
                    <table id="customer-list" class="table table-bordered table-hover wb mbtable table-striped">
                        <thead>
                        <tr>
                            <th>昵称</th>
                            <th>性别</th>
                            <th>登录城市</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody id="customer-body">
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                    <nav id="page-controller" class="clearfix">
                        <ul class="pagination pull-right">

                        </ul>
                    </nav>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default modal-close" data-dismiss="modal">关闭</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
    <div id="table-row" style="display: none">
        <tr class="customer-row">
            <td class="nickname"></td>
            <td class="sex"></td>
            <td class="city"></td>
            <td class="status"></td>
            <td class="opt"></td>
        </tr>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector();

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
    })(jQuery);

    document.getElementById('upload-head-pic').onchange = function(evt) {
        // 如果浏览器不支持FileReader，则不处理
        if (!window.FileReader) return;
        var files = evt.target.files;

        for (var i = 0, f; f = files[i]; i++) {
            if (!f.type.match('image.*')) {
                continue;
            }

            var reader = new FileReader();

            reader.onload = (function(theFile) {
                return function(e) {
                    // img 元素
                    document.getElementById('previewImage').src = e.target.result;
                };
            })(f);

            reader.readAsDataURL(f);
        }
    }

    document.getElementById('upload-certificate-pic').onchange = function(evt) {
        // 如果浏览器不支持FileReader，则不处理
        if (!window.FileReader) return;
        var files = evt.target.files;

        for (var i = 0, f; f = files[i]; i++) {
            if (!f.type.match('image.*')) {
                continue;
            }

            var reader = new FileReader();

            reader.onload = (function(theFile) {
                return function(e) {
                    // img 元素
                    document.getElementById('previewImage').src = e.target.result;
                };
            })(f);

            reader.readAsDataURL(f);
        }
    }
</script>