
<style>
</style>
<script src="<?php echo $this->jsPath("action/manage/user-create.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/manage/user-create.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/manage/user-create.js"); ?>"></script>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label>微信ID：</label>
            <span>暂未微信登录及指定用户</span>
            <a id="btn-link-user" class="btn btn-success" href="javascript:void(0)">绑定微信用户</a>
        </div>
        <div class="form-group">
            <label>微信昵称：</label>
            <span>暂未微信登录及指定用户</span>
        </div>
        <div class="form-group">
            <label>性别：</label>
            <span>暂未微信登录及指定用户</span>
        </div>
    </div>
    <div class="col-md-8">
        <form role="form" method="post" >
            <div class="form-group">
                <label>姓名：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>出生日期：</label>
                <input type="text" class="form-control" id="birthday" name="birthday" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>籍贯：</label>
                <input type="text" class="form-control" id="place" name="place" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>学历：</label>
                <input type="text" class="form-control" id="educational" name="educational" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>证书：</label>
                <input type="text" class="form-control" id="certificate" name="certificate" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>联系电话：</label>
                <input type="text" class="form-control" id="phone" name="phone" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>身份证号：</label>
                <input type="text" class="form-control" id="code" name="code" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>电子邮箱：</label>
                <input type="text" class="form-control" id="email" name="email" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>微信：</label>
                <input type="text" class="form-control" id="wechat" name="wechat" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>QQ：</label>
                <input type="text" class="form-control" id="qq" name="qq" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>所在城市：</label>
                <input type="text" class="form-control" id="location" name="location" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>授课区域：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->regions as $region): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $region->id ?>" type="checkbox" name="region[]" value="<?php echo $region->id ?>"/> <label class="marginright10px" for="<?php echo $region->id ?>"><?php echo $region->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->regions) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-region-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以授课区域， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>擅长瑜伽：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->categorys as $category): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $category->id ?>" type="checkbox" name="category[]" value="<?php echo $category->id ?>"/> <label class="marginright10px" for="<?php echo $category->id ?>"><?php echo $category->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->categorys) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-category-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>授课类型：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->lessons as $lesson): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $lesson->id ?>" type="checkbox" name="lesson[]" value="<?php echo $lesson->id ?>"
                            <?php
                            foreach ($this->model->lesson as $p) {
                                if ($lesson->id == $p->id) {
                                    echo "checked='checked'";

                                    break;
                                }
                            }
                            ?>/> <label class="marginright10px" for="<?php echo $lesson->id ?>"><?php echo $lesson->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->lessons) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-lesson-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽课程可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>银行：</label>
                <input type="text" class="form-control" id="bank" name="bank" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>帐号：</label>
                <input type="text" class="form-control" id="bank_code" name="bank_code" data-toggle="popover" value="">
            </div>
            <div class="form-group">
                <label>老师照片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div class="form-group">
                <label>简介：</label>
                <textarea row="10" class="form-control" id="description" name="description"></textarea>
            </div>
            <div class="form-group">
                <div class="col-md-8">
                    <div class="btb">
                        <button type="button" id="btn-skill-add" class="btn btn-success" href="javascript:void(0)">新建评估分数</button>
                    </div>
                    <div id="skill-list" class="col-md-8">
                    </div>
                </div>
            </div>
            <input type="hidden" id="skills" name="skills">
            <div class="clear-10"></div>
            <button type="submit" id="save-btn"  class="btn btn-default">确认提交</button>
        </form>
    </div>
    <div id="skill-model" style="display: none">
        <div class="form-group">
            <label>评估名称：</label>
            <input type="text" class="skill-name" data-toggle="popover" value="">
            <label>评估分数：</label>
            <input type="text" class="skill-value" data-toggle="popover" value="">
            <button class="btn-skill-remove" type="button">删除评估</button>
        </div>
    </div>
    <div id="user-list" style="display: none">

    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector();

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
    })(jQuery);
</script>