
<style>
</style>
<script src="<?php echo $this->jsPath("tools/String.js"); ?>"></script>
<script src="<?php echo $this->jsPath("action/manage/teacher-save.js"); ?>"></script>
<script src="<?php echo $this->jsPath("api/customer.js"); ?>"></script>
<script src="<?php echo $this->jsPath("entity/customer.js"); ?>"></script>
<script src="<?php echo $this->jsPath("delegate/manage/teacher-save.js"); ?>"></script>
<script src="<?php echo $this->jsPath("controller/manage/teacher-save.js"); ?>"></script>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label>微信ID：</label>
            <span class="span-openid">
                <?php
                    if ($this->model->openid) {
                        echo $this->model->openid;
                    }
                    else {
                        echo "暂未微信登录及指定用户";
                    }
                ?>
            </span>
            <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#customer-list">绑定微信用户</button>
        </div>
        <div class="form-group">
            <label>微信昵称：</label>
            <span class="span-nickname">
                <?php
                    if ($this->model->openid) {
                        echo $this->model->nickname;
                    }
                    else {
                        echo "暂未微信登录及指定用户";
                    }
                ?>
            </span>
        </div>
        <div class="form-group">
            <label>性别：</label>
            <span class="span-sex">
                <?php
                    if ($this->model->openid) {
                        echo $this->sex;
                    }
                    else {
                        echo "暂未微信登录及指定用户";
                    }
                ?>
            </span>
        </div>
    </div>
    <div class="col-md-8">
        <form role="form" method="post" >
            <input type="hidden" id="wxid" name="wxid">
            <div class="form-group">
                <label>姓名：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $this->model->name ?>" required="required" oninvalid="setCustomValidity('必须填写老师姓名!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>出生日期：</label>
                <input type="date" class="form-control" id="birthday" name="birthday" data-toggle="popover" value="<?php echo $this->model->birthday ?>" required="required" oninvalid="setCustomValidity('必须填写出生日期!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>籍贯：</label>
                <input type="text" class="form-control" id="place" name="place" data-toggle="popover" value="<?php echo $this->model->place ?>" required="required" oninvalid="setCustomValidity('必须填写籍贯!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>学历：</label>
                <input type="text" class="form-control" id="educational" name="educational" data-toggle="popover" value="<?php echo $this->model->educational ?>" required="required" oninvalid="setCustomValidity('必须填写学历!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>证书：</label>
                <input type="text" class="form-control" id="certificate" name="certificate" data-toggle="popover" value="<?php echo $this->model->certificate ?>" required="required" oninvalid="setCustomValidity('必须填写证书!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>联系电话：</label>
                <input type="number" class="form-control" id="phone" name="phone" data-toggle="popover" maxlength="11" value="<?php echo $this->model->phone ?>" required="required" oninvalid="setCustomValidity('必须填写联系电话!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>身份证号：</label>
                <input type="text" class="form-control" id="code" name="code" data-toggle="popover" maxlength="18" value="<?php echo $this->model->code ?>" required="required" oninvalid="setCustomValidity('必须填写身份证号!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>电子邮箱：</label>
                <input type="email" class="form-control" id="email" name="email" data-toggle="popover" value="<?php echo $this->model->email ?>" required="required" oninvalid="setCustomValidity('必须填写电子邮箱!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>微信：</label>
                <input type="text" class="form-control" id="wechat" name="wechat" data-toggle="popover" value="<?php echo $this->model->wechat ?>" required="required" oninvalid="setCustomValidity('必须填写微信号!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>QQ：</label>
                <input type="number" class="form-control" id="qq" name="qq" data-toggle="popover" value="<?php echo $this->model->qq ?>" required="required" oninvalid="setCustomValidity('必须填写QQ号!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>教学年数：</label>
                <input type="number" class="form-control" id="years" name="years" maxlength="15" data-toggle="popover" value="<?php echo $this->model->years ?>" required="required" oninvalid="setCustomValidity('必须填写教学年数!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>授课价格(小时)：</label>
                <input type="number" class="form-control money" id="price" name="price" data-toggle="popover" value="<?php echo $this->model->price ?>" required="required" oninvalid="setCustomValidity('必须填写授课价格!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>所在城市：</label>
                <input type="text" class="form-control" id="location" name="location" data-toggle="popover" value="<?php echo $this->model->location ?>" required="required" oninvalid="setCustomValidity('必须填写所在城市!');" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>授课区域：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->regions as $region): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $region->id ?>" type="checkbox" name="region[]" value="<?php echo $region->id ?>"
                        <?php
                            foreach ($this->model->region as $r) {
                                if ($region->id == $r->id) {
                                    echo "checked='checked'";

                                    break;
                                }
                            }
                        ?>
                        /> <label class="marginright10px" for="<?php echo $region->id ?>"><?php echo $region->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->regions) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-region-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以授课区域， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>擅长瑜伽：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->categorys as $category): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $category->id ?>" type="checkbox" name="category[]" value="<?php echo $category->id ?>"
                            <?php
                                foreach ($this->model->category as $c) {
//                                    if ($category->id == $c->id) {
//                                        echo "checked='checked'";
//
//                                        break;
//                                    }

                                    echo $c->name;
                                }
                            ?>
                        /> <label class="marginright10px" for="<?php echo $category->id ?>"><?php echo $category->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->lessons) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-category-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽种类可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>授课类型：</label>
            </div>
            <div class="form-group">
                <?php foreach ($this->lessons as $lesson): ?>
                    <div  style="float:left" >
                        <input id="<?php echo $lesson->id ?>" type="checkbox" name="lesson[]" value="<?php echo $lesson->id ?>"
                            <?php
                            foreach ($this->model->lesson as $p) {
                                if ($lesson->id == $p->id) {
                                    echo "checked='checked'";

                                    break;
                                }
                            }
                            ?>/> <label class="marginright10px" for="<?php echo $lesson->id ?>"><?php echo $lesson->name ?></label>
                    </div>
                <?php endforeach; ?>
                <?php
                if (count($this->lessons) == 0) {
                    echo '<a href="' . $this->url(array(), "manage-lesson-list-home") . '" class="butn btn-default" target="_blank">暂时没有瑜伽课程可以关联， 现在添加</a>';
                }
                ?>
            </div>
            <div class="clear-10"></div>
            <div class="form-group">
                <label>银行：</label>
                <input type="text" class="form-control" id="bank" name="bank" data-toggle="popover" value="<?php echo $this->model->bank ?>" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>帐号：</label>
                <input type="number" class="form-control" id="bank_code" name="bank_code" data-toggle="popover" value="<?php echo $this->model->bank_code ?>" oninput="setCustomValidity('');">
            </div>
            <div class="form-group">
                <label>老师照片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div class="form-group">
                <label>简介：</label>
                <textarea row="10" class="form-control" id="description" name="description"><?php echo $this->model->description ?></textarea>
            </div>
            <div class="form-group">
                <label>授课经历：</label>
                <textarea row="10" class="form-control" id="experience" name="experience"></textarea>
            </div>
            <div class="form-group">
                <div class="col-md-8">
                    <div class="btb">
                        <button type="button" id="btn-skill-add" class="btn btn-default">新建评估分数</button>
                    </div>
                    <div id="skill-list" class="col-md-8">
                        <?php foreach($this->model->skill as $skill): ?>
                            <div class="form-group">
                                <label>评估名称：</label>
                                <input type="text" class="skill-name" data-toggle="popover" value="<?php echo $skill->name ?>">
                                <label>评估分数：</label>
                                <input type="text" class="skill-value" data-toggle="popover" value="<?php echo $skill->value ?>">
                                <button class="btn-skill-remove" type="button">删除评估</button>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <input type="hidden" id="skills" name="skills">
            <div class="clear-10"></div>
            <button type="submit" id="save-btn"  class="btn btn-default">确认提交</button>
        </form>
    </div>
    <div id="skill-model" style="display: none">
        <div class="form-group">
            <label>评估名称：</label>
            <input type="text" class="skill-name" data-toggle="popover" value="">
            <label>评估分数：</label>
            <input type="text" class="skill-value" data-toggle="popover" value="">
            <button class="btn-skill-remove" type="button">删除评估</button>
        </div>
    </div>
    <div class="modal fade" id="customer-list" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        用户列表
                    </h4>
                </div>
                <div class="modal-body">
                    <label>微信昵称：</label>
                    <input type="text" id="wx-name" data-toggle="popover" value=""><button type="button" id="bang-customer" >查询</button>
                    <table id="customer-list" class="table table-bordered table-hover wb mbtable table-striped">
                        <thead>
                        <tr>
                            <th>昵称</th>
                            <th>性别</th>
                            <th>登录城市</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody id="customer-body">
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                    <nav id="page-controller" class="clearfix">
                        <ul class="pagination pull-right">

                        </ul>
                    </nav>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default modal-close" data-dismiss="modal">关闭</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector(false, <?php echo json_encode($this->photo) ?>);

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });
    })(jQuery);
</script>